INSERT INTO production.fact_milb_player_game (
    player_id, game_pk, player_role,
    game_date, season, team_id, team_name,
    sport_id, level, parent_org_id,
    bat_pa, bat_ab, bat_h, bat_2b, bat_3b, bat_hr,
    bat_r, bat_rbi, bat_bb, bat_k, bat_hbp,
    bat_sb, bat_cs, bat_tb, bat_errors
)
SELECT
    b.batter_id              AS player_id,
    b.game_pk,
    'batter'                 AS player_role,
    b.game_date,
    b.season,
    MAX(b.team_id)           AS team_id,
    MAX(b.team_name)         AS team_name,
    MAX(b.sport_id)          AS sport_id,
    MAX(b.level)             AS level,
    MAX(b.parent_org_id)     AS parent_org_id,
    SUM(b.plate_appearances) AS bat_pa,
    SUM(b.at_bats)           AS bat_ab,
    SUM(b.hits)              AS bat_h,
    SUM(b.doubles)           AS bat_2b,
    SUM(b.triples)           AS bat_3b,
    SUM(b.home_runs)         AS bat_hr,
    SUM(b.runs)              AS bat_r,
    SUM(b.rbi)               AS bat_rbi,
    SUM(b.walks)             AS bat_bb,
    SUM(b.strikeouts)        AS bat_k,
    SUM(b.hit_by_pitch)      AS bat_hbp,
    SUM(b.sb)                AS bat_sb,
    SUM(b.caught_stealing)   AS bat_cs,
    SUM(b.total_bases)       AS bat_tb,
    SUM(b.errors)            AS bat_errors
FROM staging.milb_batting_game_logs b
GROUP BY b.batter_id, b.game_pk, b.game_date, b.season
ON CONFLICT (player_id, game_pk, player_role) DO UPDATE
SET game_date     = EXCLUDED.game_date,
    season        = EXCLUDED.season,
    team_id       = EXCLUDED.team_id,
    team_name     = EXCLUDED.team_name,
    sport_id      = EXCLUDED.sport_id,
    level         = EXCLUDED.level,
    parent_org_id = EXCLUDED.parent_org_id,
    bat_pa        = EXCLUDED.bat_pa,
    bat_ab        = EXCLUDED.bat_ab,
    bat_h         = EXCLUDED.bat_h,
    bat_2b        = EXCLUDED.bat_2b,
    bat_3b        = EXCLUDED.bat_3b,
    bat_hr        = EXCLUDED.bat_hr,
    bat_r         = EXCLUDED.bat_r,
    bat_rbi       = EXCLUDED.bat_rbi,
    bat_bb        = EXCLUDED.bat_bb,
    bat_k         = EXCLUDED.bat_k,
    bat_hbp       = EXCLUDED.bat_hbp,
    bat_sb        = EXCLUDED.bat_sb,
    bat_cs        = EXCLUDED.bat_cs,
    bat_tb        = EXCLUDED.bat_tb,
    bat_errors    = EXCLUDED.bat_errors;


INSERT INTO production.fact_milb_player_game (
    player_id, game_pk, player_role,
    game_date, season, team_id, team_name,
    sport_id, level, parent_org_id,
    pit_ip, pit_er, pit_r, pit_h, pit_bb, pit_k, pit_hr, pit_bf,
    pit_w, pit_l, pit_sv, pit_hld, pit_bs,
    pit_pitches, pit_strikes, pit_is_starter
)
SELECT
    p.pitcher_id              AS player_id,
    p.game_pk,
    'pitcher'                 AS player_role,
    p.game_date,
    p.season,
    MAX(p.team_id)            AS team_id,
    MAX(p.team_name)          AS team_name,
    MAX(p.sport_id)           AS sport_id,
    MAX(p.level)              AS level,
    MAX(p.parent_org_id)      AS parent_org_id,
    SUM(p.innings_pitched)    AS pit_ip,
    SUM(p.earned_runs)        AS pit_er,
    SUM(p.runs)               AS pit_r,
    SUM(p.hits)               AS pit_h,
    SUM(p.walks)              AS pit_bb,
    SUM(p.strike_outs)        AS pit_k,
    SUM(p.home_runs)          AS pit_hr,
    SUM(p.batters_faced)      AS pit_bf,
    SUM(p.wins)               AS pit_w,
    SUM(p.losses)             AS pit_l,
    SUM(p.saves)              AS pit_sv,
    SUM(p.holds)              AS pit_hld,
    SUM(p.blown_saves)        AS pit_bs,
    SUM(p.number_of_pitches)  AS pit_pitches,
    SUM(p.strikes)            AS pit_strikes,
    BOOL_OR(p.is_starter)     AS pit_is_starter
FROM staging.milb_pitching_game_logs p
GROUP BY p.pitcher_id, p.game_pk, p.game_date, p.season
ON CONFLICT (player_id, game_pk, player_role) DO UPDATE
SET game_date      = EXCLUDED.game_date,
    season         = EXCLUDED.season,
    team_id        = EXCLUDED.team_id,
    team_name      = EXCLUDED.team_name,
    sport_id       = EXCLUDED.sport_id,
    level          = EXCLUDED.level,
    parent_org_id  = EXCLUDED.parent_org_id,
    pit_ip         = EXCLUDED.pit_ip,
    pit_er         = EXCLUDED.pit_er,
    pit_r          = EXCLUDED.pit_r,
    pit_h          = EXCLUDED.pit_h,
    pit_bb         = EXCLUDED.pit_bb,
    pit_k          = EXCLUDED.pit_k,
    pit_hr         = EXCLUDED.pit_hr,
    pit_bf         = EXCLUDED.pit_bf,
    pit_w          = EXCLUDED.pit_w,
    pit_l          = EXCLUDED.pit_l,
    pit_sv         = EXCLUDED.pit_sv,
    pit_hld        = EXCLUDED.pit_hld,
    pit_bs         = EXCLUDED.pit_bs,
    pit_pitches    = EXCLUDED.pit_pitches,
    pit_strikes    = EXCLUDED.pit_strikes,
    pit_is_starter = EXCLUDED.pit_is_starter;
